# Generated by Django 5.1 on 2024-08-12 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='time',
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='rfid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Event_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.eventrecord')),
            ],
        ),
    ]
